cc_test(
  name = "grace_lexer_tests",
  size = "small",
  srcs = [
    "grace_lexer_memory.cc",
    "grace_lexer_correctness.cc",
  ],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
    "//src:grace"
  ],
)
